[project]
name = "alphalibras-nuclic"
version = "0.1.0"
description = "API e interface web para ensino interativo de Libras com reconhecimento de sinais por câmera."
authors = [
    { name = "Anderson Ivanildo", email = "andersonivanildo@protonmail.com" }
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "fastapi[all]>=0.118.0,<0.119.0",
    "kagglehub>=0.3.13,<0.4.0",
    "mediapipe==0.10.21",
    "opencv-python<4.9",
    "pandas>=2.3.2,<3.0.0",
    "scikit-learn>=1.7.2,<2.0.0",
    "tflite-runtime-nightly>=2.20.0.dev20250409,<3.0.0",
]

[project.scripts]
alphalibras-api = "alphalibras_app.main:run"

[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
alphalibras_app = [
    "index.html",
    "static/*",
    "static/maos/*",
    "models/*",
    "data/*",
]
